import Inputmask from "inputmask";

export const json = {
  questions: [
    {
      type: "radiogroup",
      name: "age",
      title: "What is your age?",
      isRequired: true,
      colCount: 1,
      choices: [
        "under 18",
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55-64",
        "65 or over",
      ],
    },
    {
      type: "dropdown",
      name: "industry",
      title: "What industry do you work in?",
      isRequired: true,
      colCount: 3,
      choices: [
        "Accounting, Banking & Finance",
        "Aerospace",
        "Agriculture or Forestry",
        "Art & Design",
        "Auto Repair",
        "Business or Consulting",
        "Computing or Tech",
        "Education",
        "Energy",
        "Engineering or Manufacturing",
        "Entertainment",
        "Environment",
        "Food",
        "Government and Public Administration",
        "Health care",
        "Hospitality & Events",
        "Insurance",
        "Law or Law Enforcement",
        "Leisure, Sport & Tourism",
        "Library",
        "Marketing, Advertising & PR",
        "Media & Digital",
        "Nonprofits",
        "Other",
        "Property or Construction",
        "Publishing",
        "Recruitment or HR",
        "Research",
        "Retail",
        "Sales",
        "Social Work",
        "Transport or Logistics",
        "Utilities & Telecommunications",
      ],
    },
    {
      name: "job_title",
      type: "text",
      title: "What is your exact job title?",
      placeHolder: "...",
      isRequired: true,
    },
    {
      name: "annual_salary",
      type: "text",
      inputMask: "currency",
      title: "What is your annual income (in USD, please)?",
      placeHolder: "...",
      isRequired: true,
      validators: [
        {
          type: "numeric",
          minValue: 0,
          maxValue: 10000000,
        },
      ],
    },
    {
      type: "radiogroup",
      name: "currency",
      title: "What currency is your income in (should be USD)?",
      isRequired: true,
      colCount: 1,
      choices: ["USD"],
    },
    {
      type: "radiogroup",
      name: "work_experience",
      title: "How many years of work experience do you have (professional) ?",
      isRequired: true,
      colCount: 1,
      choices: [
        "0 - 1 years",
        "11 - 20 years",
        "2 - 4 years",
        "21 - 30 years",
        "31 - 40 years",
        "41 years or more",
        "5 - 7 years",
        "8 - 10 years",
      ],
    },
    {
      type: "comment",
      name: "job_context",
      title:
        "If you have any additional context for your job, please put it here:",
    },
    {
      name: "additional_income",
      type: "text",
      inputMask: "currency",
      title:
        "Please list any additional income or monetary compensation you received in a year:",
      placeHolder: "...",
      isRequired: true,
      validators: [
        {
          type: "numeric",
          minValue: 0,
          maxValue: 10000000,
        },
      ],
    },
    {
      type: "comment",
      name: "additional_income_context",
      title:
        "If you have any additional context for your extra/added income, please put it here:",
    },
    {
      type: "dropdown",
      name: "country",
      title: "What country do you work in?",
      isRequired: true,
      choicesByUrl: {
        url: "https://restcountries.eu/rest/v2/all",
        valueName: "name",
      },
    },
    {
      type: "dropdown",
      name: "state",
      title:
        "If you work from the United States of America, which state/district are you from?",
      isRequired: true,
      colCount: 3,
      choices: [
        "Alaska",
        "Alabama",
        "Arkansas",
        "American Samoa",
        "Arizona",
        "California",
        "Colorado",
        "Connecticut",
        "District of Columbia",
        "Delaware",
        "Florida",
        "Georgia",
        "Guam",
        "Hawaii",
        "Iowa",
        "Idaho",
        "Illinois",
        "Indiana",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Massachusetts",
        "Maryland",
        "Maine",
        "Michigan",
        "Minnesota",
        "Missouri",
        "Mississippi",
        "Montana",
        "North Carolina",
        " North Dakota",
        "Nebraska",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "Nevada",
        "New York",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Puerto Rico",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Virginia",
        "Virgin Islands",
        "Vermont",
        "Washington",
        "Wisconsin",
        "West Virginia",
        "Wyoming",
      ],
    },
    {
      name: "city",
      type: "text",

      title: "What city do you work from ?",
      placeHolder:
        "Leave this box blank if you do not wish to share this information",

      validators: [
        {
          type: "text",
          maxLength: 35,
        },
      ],
    },
    {
      type: "radiogroup",
      name: "highest_level_of_education",
      title: "What is your highest level of completed education?",
      isRequired: true,
      colCount: 1,
      choices: [
        "College degree",
        "High School",
        "Master's degree",
        "PhD",
        "Professional degree (MD, JD, etc.)",
        "Some college",
      ],
    },
    {
      type: "radiogroup",
      name: "gender",
      title: "What is your gender?",
      isRequired: true,
      colCount: 1,
      choices: ["Man", "Non-binary", "Woman", "Other or prefer not to answer"],
    },
    {
      type: "checkbox",
      name: "race",
      title: "What is your race  (Choose all that apply)?",
      isRequired: true,
      colCount: 1,
      choices: [
        "Asian or Asian American",
        "Black or African American",
        "Hispanic Latino or Spanish origin",
        "Middle Eastern or Northern African",
        "Native American or Alaska Native",
        "White",
        "Another option not listed here or prefer not to answer",
      ],
    },
  ],
};
